[package]
name = "shosha256"
description = "A sha256 previewer I made just for fun..."
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
sha256 = { version = "1.5.0", default-features = false }
termsize = "0.1"
