[package]
name = "shosha256"
description = "A sha256 previewer I made just for fun..."
version = "0.2.2"
license = "MIT"
edition = "2021"

[dependencies]
colored = "2.2.0"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
sha2 = "0.10.8"
termsize = "0.1"

[features]
no-color = ["colored/no-color"]
